services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
#     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    container_name: pipeline-tp-foyer
    image: cyrineattia/tp-foyer:5.0.0
    ports:
      - 8089:8089
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "management.endpoints.web.exposure.include": "*",
          "management.endpoint.prometheus.enabled": true
        }
    stdin_open: true
    tty: true

volumes:
  db:




#services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=db
##      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#
#    ports:
#      - "3307:3306"
#    volumes:
#      - db:/var/lib/mysql
#
#  app-timesheet:
#    depends_on:
#      - mysqldb
#    image: cyrineattia/tp-foyer:1.0.0
#    restart: on-failure
#    ports:
#      - "8091:8089"
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
#        "spring.datasource.username" : "root",
#        "spring.datasource.password" : "root"
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    stdin_open: true
#    tty: true
#
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    depends_on:
#      - app-timesheet
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3000:3000"
##    volumes:
##      - ./grafana.ini:/etc/grafana/grafana.ini
##    depends_on:
##      - prometheus
#
#  node-exporter:
#    image: prom/node-exporter
#    container_name: node-exporter
#    ports:
#      - "9100:9100"
#volumes:
#  db:
#
#networks:
#  default:
#    name: foyer-network